### ISSUE TITLE
KnowledgeSpaceNet API 需求：节点查询方法

### ISSUE THREAD

**Issue by ben7th** [mindpin/knowledge-space-net-lib#6]
KnowledgeSpaceNet 类上需要一个实例方法用于查询状态节点

``` ruby
knowledge_space_node = knowledge_space_net.get_space_node(knowledge_nodes)
# 传入一个知识节点数组，如果当前知识空间网络的空间节点里有对应这些知识节点的空间节点，则返回对应空间节点，否则返回nil
```

**Comment by ben7th** [comment]
对实现效率的建议：

``` ruby
ids = knowledge_nodes.uniq.sort.map(&:id)
key = ids.hash
```

我们可以将一组知识节点的id取出，去重排序后，获得它的hash值，作为KnowledgeSpaceNet类某个实例变量的key。

这样，实现 knowledge_space_net.get_space_node(knowledge_nodes) 方法时，我们就可以利用这个key快速地找到对应节点，实现时间效率比较高的查询。

**Comment by ben7th** [comment]
在根据 knowledge_net 计算对应的 knowledge_space_net 时，会按以下的方式进行构建

``` ruby
knowledge_space_net = KnowledgeSpaceNet.new(knowledge_net)
knowledge_space_net.knowledge_space_nodes = []

# .... 根据各种遍历计算并构建出 space_node
space_node = KnowledgeSpaceNode.new(id, knowledge_nodes)

# 会反复调用类似以下的方法来添加节点
knowledge_space_net.add_node(space_node)
space_node.add_child(child_space_node)
```

因此对应的实例上需要有这样的实例方法。

而且这样添加的节点要能够通过 knowledge_space_net.get_space_node(knowledge_nodes) 查到

**Comment by fushang318** [comment]
# 新建 knowledge_space_net

knowledge_space_net = KnowledgeSpaceNet.new(knowledge_net)

# 初始化后 knowledge_space_nodes 是空数组（未实现）

knowledge_space_net.knowledge_space_nodes.should == []

# KnowledgeSpaceNode 的创建方法

space_node = KnowledgeSpaceNode.new(id, knowledge_nodes)

# 增加 space_node（未实现）

knowledge_space_net.add_node(space_node)

# 类方法，给两个 space_node 建立关系

KnowledgeSapceNode.add_relaction(parent_space_node, child_space_node)
